config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }
  
  scope module: :public do
  root to: "homes#top"
  get 'homes/about' => 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/search", to: "searches#search"

  resources :posts, only: [:new, :create, :destroy, :index, :show, :edit, :update] do
    resources :comments, only: [:index, :show, :create, :destroy, :update]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :users, only: [:mypage, :show, :destroy, :update, :edit, :index] do
    resource :relationships, only: [:create, :destroy]
    resources :favorites, only: [:index]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'

    member do
      patch 'release'
      patch 'nonrelease'
    end
  end

  resources :posts_type, only: [:index, :show, :create, :destroy, :update]
  resources :chats, only: [:create, :destroy, :index, :show]
  resources :bookmarks, only: [:create, :destroy]
  resources :follows, only: [:create, :destroy, :followings, :followers]
  resources :chats, only: [:show, :create]
end
  

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    get 'dashboards', to: 'dashboards#show'
    resources :users, only: [:show, :index, :update, :destroy]
    root to: "homes#top"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise authentication_keys: [:email] 
  
  validates :email, presence: true, length: { minimum: 2 }
  validates :name, uniqueness: true, length: { maximum: 20 }
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 300 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true, length:{maximum:400}
  validates :body, presence: true
  # validates :image, presence: true

  scope :active_posts, -> { joins(:user).where(user:  {status: 1, is_deleted: false}) }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  # 単体投稿用
  def get_image(height, width)
    if images.attached?
      images.first.variant(resize_to_limit: [height, width]).processed # 最初の1枚を取得
    else
      file_path = Rails.root.join('app/assets/images3/no_image.jpg') # デフォルト画像
      ActiveStorage::Blob.create_and_upload!(
        io: File.open(file_path),
        filename: 'no_image.jpg',
        content_type: 'image/jpeg'
      ).variant(resize_to_limit: [height, width]).processed
    end
  end
  
  # 複数投稿の場合
  def get_images(height, width)
    return_images = []
    if images.attached?
      images.each do |image|
        return_images << image.variant(resize_to_limit: [height, width]).processed # 最初の1枚を取得
      end
    else
      file_path = Rails.root.join('app/assets/images3/no_image.jpg') # デフォルト画像
      image = ActiveStorage::Blob.create_and_upload!(
        io: File.open(file_path),
        filename: 'no_image.jpg',
        content_type: 'image/jpeg'
      ).variant(resize_to_limit: [height, width]).processed
      return_images << image
    end
    return_images
  end
  

  def self.search_for(content, method)
    if method == 'perfect'
      Post.where(title: content)
      # ここだけエラーが起きて苦戦
    elsif method == 'forward'
      Post.where('title or body LIKE ?', content+'%')
    elsif method == 'backward'
      Post.where('title or body LIKE ?', '%'+content)
    else
      Post.where('title or body LIKE ?', '%'+content+'%')
    end
  end
end

app/models/post_type.rb
class PostType < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  scope :active_users, -> { where(status: 1, is_deleted: false) }
        
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image
  #has_many :posts, through: :favorites
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  enum status:{nonreleased: 0, released: 1}

  # 自分がフォローされる側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
    
  # 自分がフォローする側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed



  validates :email, uniqueness: true, presence: true, length: { minimum: 2 }
  validates :username, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :profile_description, length: { maximum: 50 }

    # 退会済みのユーザーはログイン不可
    def active_for_authentication?
      super && !is_deleted
    end
  
  def get_profile_image(height, width)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images3/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [height, width]).processed
  end
  
 
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(username: content)
    elsif method == 'forward'
      User.where('username LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('username LIKE ?', '%' + content)
    else
      User.where('username LIKE ?', '%' + content + '%')
    end
  end


  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
  def index
    @users = User.page(params[:page]).per(6)
    #@users = User.all
  end

  def show
    @users = User.find(params[:user_id])
    @posts = @user.posts
  end
end
  

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboards/index.html.erb
<div class="container mt-3 font">
  <div class="row d-flex justify-content-center">
    <div class="col-10">
      <h4 class="mb-4 mt-4 text-center ">会員一覧</h4>
      
      <!-- テーブル -->
      <table class="table table-striped table-hover shadow-sm">
        <thead class="table text-center" style="background-color: #cbd0d3;">
          <tr>
            <th scope="col">氏名</th>
            <th scope="col">メールアドレス</th>
            <th scope="col">ステータス</th>
            <th scope="col">公開・非公開</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr class="align-middle text-center">
              <td><u><%= link_to user.username, admin_user_path(user), class: "text-decoration-none text-dark fw-bold" %></u></td>
              <td><%= user.email %></td>
              <td>
                <% if user.is_deleted %>
                  <%= link_to '退会済み', admin_user_path(user), method: :patch, 
                    class: "btn btn-sm btn-outline-secondary", 
                    data: { confirm: '本当に復元しますか？' } %>
                <% else %>
                  <%= link_to 'アクティブ', admin_user_path(user), method: :delete, 
                    class: "btn btn-sm btn-outline-info", 
                    data: { confirm: '本当に退会させますか？' } %>
                <% end %>
              </td>
              <td>
                <% if current_user != user && user.nonreleased? %>
                  <span class="text-white" style="background-color: #6c757d; padding: 5px 12px; border-radius: 10px; font-size: 0.9rem;">
                    非公開
                  </span>
                <% else %>
                  <span class=" text-white" style="background-color: #17a2b8; padding: 5px 12px; border-radius: 10px; font-size: 0.9rem;">
                    公開
                  </span>
                <% end %>
               </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <!-- ページネーション -->
      <div class="d-flex justify-content-center mt-4">
        <%= paginate @users, theme: 'bootstrap-5' %>
      </div>
    </div>
  </div>
</div>